templateDir=templates/templateapp
staticDir=static
outputDir=out/
databaseDriver=org.sqlite.JDBC
databaseConnPath=jdbc:sqlite:jakon.sqlite
databaseUser=
databasePass=
port=4567
deployMode=DEVEL
DEPLOY.type=cz.kamenitxan.jakon.core.deploy.DummyDeploy
defaultLocale=cs_CZ
MAIL.enabled=true
MAIL.host=smtp.seznam.cz
MAIL.port=465
MAIL.username=tomas@kamenitxan.eu
MAIL.password=
MAIL.tls=false
MAIL.ssl=true
MAIL.auth=true
package=cz.kamenitxan.web
appName=Kamenitxan.eu
hostname=kamenitxan.eu
emailValidator.checkDns=true
